name = "PkgCacheInspector"
uuid = "a408fb95-4068-4cfa-a7f1-12fd503bd86c"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "1.2.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
DocStringExtensions = "0.9"
MethodAnalysis = "0.4, 1"
julia = "1.12"

[extensions]
MethodAnalysisExt = "MethodAnalysis"

[weakdeps]
MethodAnalysis = "85b6ec6f-f7df-4429-9514-a64bcd9ee824"

[workspace]
projects = ["test", "docs"]
