name = "PkgCacheInspector"
uuid = "a408fb95-4068-4cfa-a7f1-12fd503bd86c"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "1.0.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
MethodAnalysis = "85b6ec6f-f7df-4429-9514-a64bcd9ee824"

[extensions]
MethodAnalysisExt = "MethodAnalysis"

[compat]
MethodAnalysis = "0.4"
julia = "1.9"

[extras]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Colors", "MethodAnalysis", "Pkg", "Test"]
